service: aws-backend-tourenvias
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x
  region: us-east-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:*
      Resource:
        - arn:aws:dynamodb:us-east-1:856055808811:table/tourenviasTabla

functions:
  hello:
    handler: src/hello.hello
    events:
      - httpApi:
          path: /
          method: get
  addConductor:
    handler: src/addConductor.addConductor
    events:
      - httpApi:
          path: /conductor
          method: post
  getConductores:
    handler: src/getConductores.getConductores
    events:
      - httpApi:
          path: /conductor
          method: get
  getConductor:
    handler: src/getConductor.getConductor
    events:
      - httpApi:
          path: /conductor/{id}
          method: get
  updateConductor:
    handler: src/updateConductor.updateConductor
    events:
      - httpApi:
          path: /conductor/{id}
          method: put
  deleteConductor:
    handler: src/deleteConductor.deleteConductor
    events:
      - httpApi:
          path: /conductor/{id}
          method: delete

resources:
  Resources:
    tourenviasTabla:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: tourenviasTabla
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
